[versions]
jetbrains-annotations = "26.0.1"
jgit = "6.7.0.202309050840-r"
# Gradle-specific
gradle-kotlin = "1.9.22"
# Testing
junit-jupiter = "5.11.3"
junit-launcher = "1.11.3"

[libraries]
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "jgit" }
# Gradle-specific
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "gradle-kotlin" }
# Testing
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-launcher" }
