[versions]
jetbrains-annotations = "24.0.1"
jgit = "6.7.0.202309050840-r"
junit-jupiter = "5.10.0"
junit-launcher = "1.10.0"

[libraries]
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "jgit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit.jupiter" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit.launcher" }
