name: Test
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        java: [17, 21]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
      - name: Gradle Build and Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build check --stacktrace --parallel
      - uses: actions/upload-artifact@v4
        if: matrix.java == 17
        with:
          name: Artifacts
          path: ./build/libs/
